name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  tests:
    name: Run OpenVidu Vue tests
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run the build process with Docker
      run: |
        sudo docker run -p 4443:4443 --rm -e OPENVIDU_SECRET=MY_SECRET openvidu/openvidu-dev:2.27.0 &
        cd openvidu-call-back-java
        mvn install
        mvn spring-boot:run &
        cd ../openvidu-call-vuetify-frontend
        npm install
        npm run dev & 
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: npm ci
    - uses: browser-actions/setup-chrome@v1
    - name: Install Playwright Browsers
      run: npx playwright install 
    - name: Run Playwright tests
      run: |
        cd tests
        npx playwright tests.spec.js
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
